Feature/medication calendar
biryuchez/team_development pull request #15
Opened 2022-09-16 21:39 UTC by DmitryXIII

Экран с календарем запланированных приемов лекарств (на фейковых данных)

2022-09-17 16:33 UTC, BeanNapkin requested changes
Выглядит симпатично. Есть замечания по clean архитектуре.

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/clean/domain/MedicationHistoryRepository.kt
> +interface MedicationHistoryRepository: GetMedicationScheduleUsecase {
Репозиторий не может наследоваться от юскейса -- это бессмысленно.
Репозиторий -- это data слой. Он ничего не должен знать о юскейсах

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/clean/domain/usecase/GetMedicationScheduleUsecase.kt
> +    fun getMedicationSchedule(): List<FakeMedicationScheduleEntity>
Реальный интерфейс юскейса не должен возвращать Fake ивенты. Он должен возвращать реальные доменные объекты, иначе теряется весь смысл.

Слои должны быть организованы так, чтобы можно было заменить репозиторий бесшовно с Fake на реальный, не меняя кода юскейса.

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/navigation/NavigationFragment.kt
> +                }
Вот это странно выглядит. Почему нельзя просто сделать `navigateToPillsList` и `navigateToSchedule` ?

Я думала, что смысл навигатора в том, чтобы инстансы фрагментов создавал он. В данном случае получается наоборот.

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/navigation/NavigationFragment.kt
> +        if (binding.bottomNavView.selectedItemId != clickedItemId) {
А от чего эта проверка защищает?

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/mainactivity/MainActivity.kt
> -                .replace(R.id.main_container, PillsListFragment())
А можешь рассказать в чем смысл переносить это все в NavigationFragment? чем старый вариант плох?

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/CalendarGridBuilder.kt
> +class CalendarGridBuilder(private val dateFormat: SimpleDateFormat) {
В этом классе все действительно запутано выглядит

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/DateListFactory.kt
> +    fun getDatesList(datesCount: Int): List<Long> {
а действительно необходимо класс на это создавать? Разве это не проще сделать приватным методом в CalendarGridBuilder?

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/ScheduleEventsItemsBuilder.kt
> +                .sortedBy { it.medicationTime }
Вот эта часть относится к бизнес логике. По сути, должна жить в репозитории в методе типа `getIntakeLog(medicationId: Int, date: Long)` Потому что сложность этого алгоритма 2N, а базы данных умеют это делать эффективно.

Фильтровать по имени лекарства не очень надежно. Правильнее использовать ID.

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/ScheduleEventsItemsBuilder.kt
> +        medicationScheduleList: List<FakeMedicationScheduleEntity>,
UI слой не должен напрямую работать с данными из Data слоя. Представь, что поменяется что-то в модели базы данных, эти изменения затронут и этот файл. Так неправильно. UI слой должен быть независим от Data.

Решить проблему можно созданием отдельно дата класса, подходящего чисто для отображения в UI. 

На данный момент он будет частично дублировать то, что есть в Entity, но это правильно с точки зрения Clean architecture. Это обеспечить легкость рефакторинга.

Интерактор должен заниматься конвертацией данных из доменного слоя во что-то подохдящее для отображение в UI

2022-09-17 16:33 UTC, BeanNapkin commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/clean/data/local/FakeMedicationHistoryRepository.kt
> +class FakeMedicationHistoryRepository(
Репозиторий и datasource по факту одно и тоже.

2022-09-17 19:37 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/clean/domain/MedicationHistoryRepository.kt
> +interface MedicationHistoryRepository: GetMedicationScheduleUsecase {
Согласен.
Тут я не планировал проектировать юзкейсы и репозитории. Сейчас они накиданы "на коленке, что бы было", т.к. реального локального репозитория ещё нет. Как только будет рабочий рум - все эти классы будут удалены. Максимум будет интерактор, который из рум-репозитория будет забирать список событий.

2022-09-17 19:38 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/clean/domain/usecase/GetMedicationScheduleUsecase.kt
> +    fun getMedicationSchedule(): List<FakeMedicationScheduleEntity>
Аналогично ответу на первый коммент

2022-09-17 19:44 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/navigation/NavigationFragment.kt
> +                }
А разве в данном случае не навигатор (которым является NavigationFragment) создаёт инстансы destination-фрагментов? Или я не понял, что ты имела в ввиду про инстансы?
"Почему нельзя просто сделать navigateToPillsList и navigateToSchedule ?" - потому что здесь уходим в метод навигации по боттом навигейшн, логика отличается от навигации между другими экранами

2022-09-17 19:51 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/navigation/NavigationFragment.kt
> +        if (binding.bottomNavView.selectedItemId != clickedItemId) {
Это не защита, это, скорее, логика навигации через боттомнавинейшн. "Защита" от скидывания текущего бекстека.
Если мы на PillsList начнем создавать новое напоминание, начнем продвигаться вперёд по экранам, то клик  по иконке скинет текущий открытый экран и вернет пересозданный PillsList.
А при такой "защите" выбранный элемент боттомнавигейшн кликается только один раз, т.е. если иконка в данный момент активна - ее нельзя "перекликнуть".
В общем, вижу логичным именно такое поведение боттгмнавигешн.

2022-09-17 19:56 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/mainactivity/MainActivity.kt
> -                .replace(R.id.main_container, PillsListFragment())
Старый вариант не плох, старый вариант абсолютно равносилен этому.
Когда-то на одной из конференций видел подход "сингл-активити + флоу-фрагмент", где активити, по сути, отвечает за жизненный цикл приложения, а флоу-фрагмент выполняет роль роутера (навигатора).
Первый раз пишу такую реализацию.
Не принципиально, можем вернуть все активити. Это чисто эксперимент.

2022-09-17 19:57 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/CalendarGridBuilder.kt
> +class CalendarGridBuilder(private val dateFormat: SimpleDateFormat) {
Тут без комментариев, сам в шоке.
Все немного упростится, когда будет живой рум

2022-09-17 20:05 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/DateListFactory.kt
> +    fun getDatesList(datesCount: Int): List<Long> {
Иногда встречается мнение, что приватный метод - ошибка архитектуры.
По хорошему, либо должен быть интерфейс, и все методы должны быть оверрайдными, либо отдельный классы, представляющие нужные методы. Но тут можно спорить бесконечно.
Изначально у меня список дат именно в билдере рождался, потом решил вынести  в отдельный класс (типа сингл-респонсибилити и все такое), а сейчас понимаю, что это вообще должно лежать где-то в домейн/дата и попадать в календарь через вьюмодель.
Переделаем, когда появится живой рум.

2022-09-17 20:09 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/ScheduleEventsItemsBuilder.kt
> +                .sortedBy { it.medicationTime }
Про фильтрацию согласен на 1000%, как только будет рум, вся эта логика туда переедет.
Тяжело все это проектировать, пока перед глазами нет источника данных, приходится все эти операции высасывать из пальца. Я тоже сторонник правильных SQL-запросов, а не вот такого вот

2022-09-17 20:13 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/ui/screens/calendar/builder/ScheduleEventsItemsBuilder.kt
> +        medicationScheduleList: List<FakeMedicationScheduleEntity>,
И тут поддерживаю. Но опять перед глазами нету репозитория и таблиц. Появятся - добавим маппер из таблицы в ui-data-object

2022-09-17 20:15 UTC, DmitryXIII commented on PillsReminder/app/src/main/java/pro/fateeva/pillsreminder/clean/data/local/FakeMedicationHistoryRepository.kt
> +class FakeMedicationHistoryRepository(
Да, лишнего дал, у нас же не будет remote-источника. В любом случае - тут ответ на самый первый коммент. Это все фейки, и они будет удалены, когда появится рум-репозиторий.

2022-09-18 12:58 UTC, BeanNapkin approved these changes

2022-09-18 13:56 UTC, merged